<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'All (Result, Success and Fail) method is POST' => 'Всі операції (Результат, Успіх і Невдача) використовують метод POST',
  'Error amount.' => 'Помилка суми.',
  'Error mode.' => 'Помилка режиму',
  'Error purse.' => 'Помилка гаманця',
  'Error sign.' => 'Помилка входу',
  'Fail URL: ' => 'Хибний URL',
  'For right WebMoney settings please do follows:' => 'Для правильних налаштувань WebMoney, будь ласка, зверніть увагу:',
  'Method of sign formed is MD5' => 'Дані для входу кодуються в MD5',
  'Mode' => 'Режим',
  'Pay' => 'Оплатити',
  'Pay Form' => 'Форма оплати',
  'Pay for order #' => 'Оплата операції #',
  'Purse' => 'Гаманець',
  'Real WM mode' => 'Робочий WM режим',
  'Result URL: ' => 'URL результату',
  'Secret' => 'Пароль',
  'Settiggs' => 'Налаштування',
  'Success URL: ' => 'URL завершення',
  'Test WM mode (80% success, 20% fail)' => 'Тестовий режим WM (80% успіху, 20% невдач)',
  'Test WM mode (all fail)' => 'Тестовий режим WM (всі операції хибні)',
  'Test WM mode (all success)' => 'Тестовий режим WM (всі операції успішні)',
  'WM' => 'WM',
  'WM Pay' => 'WM Оплата',
  'WM Update' => 'WM редагування',
  'WM options successful update' => 'Параметри WM успішно оновлені',
  'WM pay fail' => 'WM оплата хибна',
  'WM pay success' => 'WM оплата успішна',
);
